// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict'

var Jest = require('@glennsl/bs-jest/src/jest.js')

describe('PaperClipService', function () {
  describe('getAll(~size)', function () {
    it.skip('', function () {
      return Promise.resolve(Jest.fail('TODO'))
    })
    return /* () */ 0
  })
  return /* () */ 0
})

/*  Not a pure module */
