// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict'

var Js_option = require('bs-platform/lib/js/js_option.js')
var PaperClipHandler = require('./PaperClipHandler.bs.js')

var dummy = {
  id: 'test-paper-clip-1',
  created_at: new Date(2018.0, 1.0, 2.0),
  updated_at: new Date(2018.0, 1.0, 2.0),
  size: 'SMALL',
}

function make (mockGetAll, mockGetById, mockAdd, mockUpdate, mockRemove) {
  return /* record */ [
    /* getAll */ Js_option.getWithDefault(function () {
      return Promise.resolve(/* array */ [dummy])
    }, mockGetAll),
    /* getById */ Js_option.getWithDefault(function () {
      return Promise.resolve(dummy)
    }, mockGetById),
    /* add */ Js_option.getWithDefault(function () {
      return Promise.resolve(dummy)
    }, mockAdd),
    /* update */ Js_option.getWithDefault(function (_, _$1) {
      return Promise.resolve(dummy)
    }, mockUpdate),
    /* remove */ Js_option.getWithDefault(function () {
      return Promise.resolve({
        success: /* true */ 1,
      })
    }, mockRemove),
  ]
}

var Service = /* module */ [/* make */ make]

function make$1 (
  allPaperClips,
  paperClip,
  addPaperClip,
  updatePaperClip,
  removePaperClip
) {
  return /* record */ [
    /* resolvers */ PaperClipHandler.resolvers,
    /* queries */ {
      allPaperClips: Js_option.getWithDefault(function (_, _$1, _$2) {
        return Promise.resolve(/* array */ [dummy])
      }, allPaperClips),
      paperClip: Js_option.getWithDefault(function (_, _$1, _$2) {
        return Promise.resolve(dummy)
      }, paperClip),
    },
    /* mutations */ {
      addPaperClip: Js_option.getWithDefault(function (_, _$1, _$2) {
        return Promise.resolve(dummy)
      }, addPaperClip),
      updatePaperClip: Js_option.getWithDefault(function (_, _$1, _$2) {
        return Promise.resolve(dummy)
      }, updatePaperClip),
      removePaperClip: Js_option.getWithDefault(function (_, _$1, _$2) {
        return Promise.resolve({
          success: /* true */ 1,
        })
      }, removePaperClip),
    },
  ]
}

var Handler = /* module */ [/* make */ make$1]

exports.dummy = dummy
exports.Service = Service
exports.Handler = Handler
/* dummy Not a pure module */
