// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict'

var Debug = require('debug')

var prefix = 'trailmap-api'

function make (label) {
  var log = Debug('trailmap-api:' + label)
  return function (message) {
    return log(message)
  }
}

var Debug$1 = /* module */ [/* prefix */ prefix, /* make */ make]

exports.Debug = Debug$1
/* debug Not a pure module */
