// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict'

var Fs = require('fs')

var schema = Fs.readFileSync(
  __dirname + '/../../graphql/schema.graphql',
  'utf8'
)

var queries = Fs.readFileSync(
  __dirname + '/../../graphql/queries.graphql',
  'utf8'
)

exports.schema = schema
exports.queries = queries
/* schema Not a pure module */
