// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict'

var Curry = require('bs-platform/lib/js/curry.js')
var PaperClip = require('./PaperClip.js')
var PaperClipService = require('./PaperClipService.js')

var resolvers = {
  PaperClip: {
    id: function (paperClip) {
      return PaperClip.Resolve[/* id */ 0](paperClip)
    },
    createdAt: function (paperClip) {
      return PaperClip.Resolve[/* createdAt */ 1](paperClip)
    },
    updatedAt: function (paperClip) {
      return PaperClip.Resolve[/* updatedAt */ 2](paperClip)
    },
    size: function (paperClip) {
      return PaperClip.Resolve[/* size */ 3](paperClip)
    },
  },
}

function make (dataProvider) {
  var service = PaperClipService.make(dataProvider)
  return /* record */ [
    /* resolvers */ resolvers,
    /* queries */ {
      allPaperClips: function (_, input) {
        var opt = input.filter
        if (opt == null) {
          return Curry._1(service[/* getAll */ 0], /* None */ 0)
        } else {
          return Curry._1(
            service[/* getAll */ 0],
            /* Some */ [PaperClip.Size[/* fromString */ 0](opt.size)]
          )
        }
      },
      paperClip: function (_, input) {
        return Curry._1(service[/* getById */ 1], input.id)
      },
    },
    /* mutations */ {
      addPaperClip: function (_, input) {
        return Curry._1(service[/* add */ 2], input.paperClip)
      },
      updatePaperClip: function (_, input) {
        return Curry._2(service[/* update */ 3], input.id, input.paperClip)
      },
      removePaperClip: function (_, input) {
        return Curry._1(service[/* remove */ 4], input.id)
      },
    },
  ]
}

exports.resolvers = resolvers
exports.make = make
/* PaperClip Not a pure module */
