// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict'

var Json_decode = require('bs-json/lib/js/src/Json_decode.js')
var Json_encode = require('bs-json/lib/js/src/Json_encode.js')

function fromString (str) {
  switch (str) {
    case 'LARGE':
      return /* Large */ 2
    case 'MEDIUM':
      return /* Medium */ 1
    case 'SMALL':
      return /* Small */ 0
    default:
      return /* Small */ 0
  }
}

function toString (size) {
  switch (size) {
    case 0:
      return 'SMALL'
    case 1:
      return 'MEDIUM'
    case 2:
      return 'LARGE'
  }
}

var Size = /* module */ [/* fromString */ fromString, /* toString */ toString]

function id (paperClip) {
  return paperClip[/* id */ 0]
}

function createdAt (paperClip) {
  return paperClip[/* createdAt */ 1].toISOString()
}

function updatedAt (paperClip) {
  return paperClip[/* updatedAt */ 2].toISOString()
}

function size (paperClip) {
  return toString(paperClip[/* size */ 3])
}

var Resolve = /* module */ [
  /* id */ id,
  /* createdAt */ createdAt,
  /* updatedAt */ updatedAt,
  /* size */ size,
]

function encode (paperClip) {
  return Json_encode.object_(
    /* :: */ [
      /* tuple */ ['id', paperClip[/* id */ 0]],
      /* :: */ [
        /* tuple */ ['createdAt', paperClip[/* createdAt */ 1].toISOString()],
        /* :: */ [
          /* tuple */ ['updatedAt', paperClip[/* updatedAt */ 2].toISOString()],
          /* :: */ [
            /* tuple */ ['size', toString(paperClip[/* size */ 3])],
            /* [] */ 0,
          ],
        ],
      ],
    ]
  )
}

function decode (json) {
  return /* record */ [
    /* id */ Json_decode.field('id', Json_decode.string, json),
    /* createdAt */ new Date(
      Json_decode.field('created_at', Json_decode.string, json)
    ),
    /* updatedAt */ new Date(
      Json_decode.field('updated_at', Json_decode.string, json)
    ),
    /* size */ fromString(Json_decode.field('size', Json_decode.string, json)),
  ]
}

exports.Size = Size
exports.Resolve = Resolve
exports.encode = encode
exports.decode = decode
/* Json_encode Not a pure module */
