// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("bs-jest/lib/js/src/jest.js");

describe("PaperClipService", (function () {
        describe("getAll(~size)", (function () {
                test.skip("", (function () {
                        return Promise.resolve(Jest.fail("TODO"));
                      }));
                return /* () */0;
              }));
        return /* () */0;
      }));

/*  Not a pure module */
