// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict'

function heartbeat (_, res) {
  res.send('ok')
  return Promise.resolve(undefined)
}

function objToJson (obj) {
  var str = JSON.stringify(obj)
  if (str !== undefined) {
    return JSON.parse(str)
  } else {
    return null
  }
}

exports.heartbeat = heartbeat
exports.objToJson = objToJson
/* No side effect */
