// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict'

function parseInt_ ($$int, string) {
  return parseInt(string, $$int)
}

exports.parseInt_ = parseInt_
/* No side effect */
