// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict'

var Js_exn = require('bs-platform/lib/js/js_exn.js')
var MomentRe = require('bs-moment/src/MomentRe.js')

function $$parseInt$1 (string) {
  return parseInt(string, 10)
}

function getOrError (error, nullable) {
  if (nullable == null) {
    return Js_exn.raiseError(error)
  } else {
    return nullable
  }
}

function decodeDate (date) {
  return MomentRe.moment(/* None */ 0, date).toDate()
}

exports.$$parseInt = $$parseInt$1
exports.getOrError = getOrError
exports.decodeDate = decodeDate
/* MomentRe Not a pure module */
