// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict'

var Dotenv = require('dotenv')
var Process = require('process')
var Js_option = require('bs-platform/lib/js/js_option.js')
var Js_primitive = require('bs-platform/lib/js/js_primitive.js')
var ParseDbUrl = require('parse-database-url')

Dotenv.config({
  silent: /* true */ 1,
})

function getEnvVar (key, fallback) {
  return Js_option.getWithDefault(
    fallback,
    Js_primitive.undefined_to_opt(Process.env[key])
  )
}

var port = parseInt(getEnvVar('PORT', '4000'), 10)

var corsHeaders = /* array */ ['Link']

var isDev = +(getEnvVar('NODE_ENV', 'development') === 'development')

var Server = /* module */ [
  /* port */ port,
  /* bodyLimit */ '100kb',
  /* corsHeaders */ corsHeaders,
  /* isDev */ isDev,
]

var url = getEnvVar(
  'DATABASE_URL',
  'postgres://trailmap:trailmap@localhost:5432/trailmap'
)

var config = ParseDbUrl(url)

var name = config.database

var username = config.user

var password = config.password

var hostname = config.host

var port$1 = config.port

var poolMin = parseInt(getEnvVar('DATABASE_POOL_MIN', '0'), 10)

var poolMax = parseInt(getEnvVar('DATABASE_POOL_MAX', '10'), 10)

var poolIdle = parseInt(getEnvVar('DATABASE_POOL_IDLE', '10000'), 10)

var Database = /* module */ [
  /* url */ url,
  /* config */ config,
  /* name */ name,
  /* username */ username,
  /* password */ password,
  /* hostname */ hostname,
  /* port */ port$1,
  /* poolMin */ poolMin,
  /* poolMax */ poolMax,
  /* poolIdle */ poolIdle,
]

exports.getEnvVar = getEnvVar
exports.Server = Server
exports.Database = Database
/*  Not a pure module */
