// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Dotenv       = require("dotenv");
var Process      = require("process");
var Js_option    = require("bs-platform/lib/js/js_option.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

Dotenv.config({
      silent: /* true */1
    });

function getEnvVar(key, fallback) {
  return Js_option.getWithDefault(fallback, Js_primitive.undefined_to_opt(Process.env[key]));
}

var port = parseInt(getEnvVar("PORT", "4000"), 10);

var corsHeaders = /* array */["Link"];

var isDev = +(getEnvVar("NODE_ENV", "development") === "development");

var Server = /* module */[
  /* port */port,
  /* bodyLimit */"100kb",
  /* corsHeaders */corsHeaders,
  /* isDev */isDev
];

var url = getEnvVar("DATABASE_URL", "postgres://username:password@localhost:5432/database");

var Database = /* module */[/* url */url];

exports.getEnvVar = getEnvVar;
exports.Server    = Server;
exports.Database  = Database;
/*  Not a pure module */
