// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict'

var Curry = require('bs-platform/lib/js/curry.js')
var HttpUtils = require('./utils/HttpUtils.js')
var Caml_array = require('bs-platform/lib/js/caml_array.js')

function decodeResults (decoder, results) {
  return Promise.resolve(
    results.map(HttpUtils.objToJson).map(Curry.__1(decoder))
  )
}

function rejectIfEmpty (decoder, error, results) {
  if (results.length !== 0) {
    return decodeResults(decoder, results)
  } else {
    return Promise.reject(new Error(error))
  }
}

function pickFirst (results) {
  return Promise.resolve(Caml_array.caml_array_get(results, 0))
}

exports.decodeResults = decodeResults
exports.rejectIfEmpty = rejectIfEmpty
exports.pickFirst = pickFirst
/* No side effect */
