// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var HttpUtils = require("./HttpUtils.js");
var Make      = require("express-promise-router");

function make() {
  var router = Make(/* () */0);
  router.get("/", HttpUtils.heartbeat);
  return router;
}

var Web = /* module */[/* make */make];

exports.Web = Web;
/* express-promise-router Not a pure module */
