// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Fs            = require("fs");
var Graphql       = require("graphql");
var TextUtils     = require("./utils/TextUtils.js");
var GraphQLScalar = require("bs-graphql-scalar/lib/js/src/GraphQLScalar.js");

var schema = Fs.readFileSync(__dirname + "/../graphql/schema.graphql", "utf8");

var queries = Fs.readFileSync(__dirname + "/../graphql/queries.graphql", "utf8");

var coreResolvers = {
  DateTime: new Graphql.GraphQLScalarType({
        name: "DateTime",
        description: "DateTime custom scalar Type",
        serialize: (function (value) {
            return value.getTime().toString();
          }),
        parseValue: (function (str) {
            return new Date(str);
          }),
        parseLiteral: (function (ast) {
            var kind = ast.kind;
            if (kind === GraphQLScalar.Language[/* intKind */0]) {
              return TextUtils.parseInt_(10, ast.value);
            } else {
              return null;
            }
          })
      })
};

exports.schema        = schema;
exports.queries       = queries;
exports.coreResolvers = coreResolvers;
/* schema Not a pure module */
