// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Cors                = require("cors");
var Chalk               = require("chalk");
var Config              = require("./Config.js");
var Router              = require("./Router.js");
var Morgan              = require("morgan");
var Express             = require("bs-express/lib/js/src/express.js");
var Make                = require("express");
var Js_option           = require("bs-platform/lib/js/js_option.js");
var BodyParser          = require("body-parser");
var Js_primitive        = require("bs-platform/lib/js/js_primitive.js");
var ApolloServerExpress = require("bs-apollo-server-express/lib/js/src/ApolloServerExpress.js");

var graphiqlMiddleware = ApolloServerExpress.createGraphiQLExpressMiddleware(/* None */0, /* None */0, /* None */0, /* None */0, "/graphql");

function onListen(exn) {
  if (exn == null) {
    console.log(Chalk.blue("telepathic") + " is listening on port " + Chalk.green(Config.Server[/* port */0].toString()));
    return /* () */0;
  } else {
    console.log(Chalk.red("Express listen error: ") + Js_option.getWithDefault("(no message)", Js_primitive.undefined_to_opt(exn.message)));
    return /* () */0;
  }
}

function start() {
  var app = Make();
  var match = Config.Server[/* isDev */3];
  if (match !== 0) {
    app.use(Morgan("dev"));
  } else {
    app.use(Morgan("combined"));
  }
  app.use(Cors({
            exposedHeaders: Config.Server[/* corsHeaders */2]
          }));
  app.use(BodyParser.json({
            limit: Config.Server[/* bodyLimit */1]
          }));
  app.use(Router.Web[/* make */0](/* () */0));
  return Express.App[/* listen */0](app, /* Some */[Config.Server[/* port */0]], /* Some */[onListen], /* () */0);
}

function main() {
  return start(/* () */0);
}

if ((require.main === module)) {
  start(/* () */0);
}

exports.graphiqlMiddleware = graphiqlMiddleware;
exports.onListen           = onListen;
exports.start              = start;
exports.main               = main;
/* graphiqlMiddleware Not a pure module */
