// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';


function heartbeat(_, res) {
  res.send("ok");
  return Promise.resolve(undefined);
}

exports.heartbeat = heartbeat;
/* No side effect */
