// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Make                          = require("express-promise-router");
var HttpUtils$ReasonExpressHeroku = require("./HttpUtils.js");

function make() {
  var router = Make(/* () */0);
  router.get("/", HttpUtils$ReasonExpressHeroku.heartbeat);
  return router;
}

var Web = /* module */[/* make */make];

exports.Web = Web;
/* express-promise-router Not a pure module */
