// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict'

var Js_mapperRt = require('bs-platform/lib/js/js_mapperRt.js')

var jsMapperConstantArray = /* array */ [
  /* tuple */ [48800667, 'LARGE'],
  /* tuple */ [311976103, 'SMALL'],
  /* tuple */ [861718677, 'MEDIUM'],
]

function sizeToJs (param) {
  return Js_mapperRt.binSearch(3, param, jsMapperConstantArray)
}

function sizeFromJs (param) {
  return Js_mapperRt.revSearch(3, jsMapperConstantArray, param)
}

var PaperClip = /* module */ [
  /* sizeToJs */ sizeToJs,
  /* sizeFromJs */ sizeFromJs,
]

exports.PaperClip = PaperClip
/* No side effect */
